---
apiVersion: v2
appVersion: 1.0.0
description: Installs Prometheus with Grafana. Sets up scrapers -> Node-Exporter, Uptimekuma, Speedtest
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 69.5.1
name: monitoring
type: application
version: 3.0.0
