---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - ingress.sops.yaml
  - limit-egress.yaml
  - namespace.yaml
  - secret.sops.yaml
  - super-secret.sops.yaml